### ISSUE TITLE
Bug? LocalWP with Atlas plugin opens endless blank command prompts one or two at a time

### ISSUE THREAD

**Issue by miacias** [DiscipleTools/Documentation#64]
When running a headless version with Atlas Plugin on Windows, blank command prompts continually open, preventing use of the computer. Please see attached video recording for more details:

https://github.com/DiscipleTools/Documentation/assets/113298622/319ea31e-115d-4e2f-8685-521ac59ca0ec

LocalWP site specs:

- web server: nginx
- php: 8.3.0
- db: MySQL 8.0.16
- WordPress: 6.4.3
- multisite: no
- Xdebug: off

Environment where bug occurs:

- processor: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
- RAM: 48.0 GB
- system type: 64-bit operating system, x64-based processor
- OS: Windows 10 Home
- OS build: 19045.4170

**Comment by corsacca** [comment]
Hey @miacias, thanks for messaging and welcome to Disciple.Tools!

We haven't explored running Discipe.Tools in headless mode. I'd love to hear more about what leads you to explore this option. Is this something we should be looking into more?

Do you get the same behavior when the Disciple.Tools theme is not installed?

**Comment by miacias** [comment]
I thought this was LocalWP? I don't recognize the theme name, but the problem doesn't occur on other operating systems

**Comment by corsacca** [comment]
@miacias this is the documentation repo for https://disciple.tools/ 
I think you can find help for your question on https://community.localwp.com/ (which is actually down for me at the moment).

**Comment by miacias** [comment]
Thanks, they were down for me at well. This repo came up when I attempted searching for them. Apologies and thanks for your help

**Comment by corsacca** [comment]
No worries! Thanks for stopping by! :)
